import React from 'react'
import { useScroll, motion, useSpring, useTransform } from 'framer-motion'

const ScrollAnimations = () => {
    const { scrollYProgress } = useScroll();

    const scaleX = useSpring(scrollYProgress)

    const background = useTransform(scrollYProgress, [0, 1], ["rgb(86, 1,245)", "rgb(1,245,13)"])

  return (
    <div>
        <motion.div style={{
            background: background,
            transformOrigin: "left",
            position: "sticky",
            top: 0,
            width: "100%",
            height: "20px",
            scaleX,
        }}/>

        <div style={{ padding: "1.2rem", margin: "auto", maxWidth: "700px"}}>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>
            <p style={{fontSize: "1.5rem"}}>Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt esse provident facere ipsum? Illo vero voluptate repellendus at ad asperiores excepturi quis, repellat temporibus, inventore nihil voluptatem doloribus aliquid. Quam quibusdam deserunt eaque amet perferendis iure ullam porro? Dolor quam id inventore, amet culpa mollitia neque, voluptatem natus aliquid officiis aperiam minima! Corporis doloribus earum, nesciunt quam dolore consequatur quis perspiciatis quidem distinctio iste officia, accusamus provident accusantium ullam, harum dolorem assumenda minus quia odit possimus nemo asperiores cumque. Vero vel inventore quam quas officia culpa eligendi magni atque libero autem, voluptatem facilis iure quia nemo eius consequatur amet quo.</p>


        </div>
    </div>
  )
}

export default ScrollAnimations